from flask import Flask, request, render_template
import os
import sys

# Adjust the import based on exactly where you saved your pipeline code
from src.pipeline.predict_pipeline import CustomData, PredictPipeline

# Initialize the Flask application
application = Flask(__name__)
app = application

# Load the models into memory ONCE when the server starts to eliminate latency
predict_pipeline = PredictPipeline()

# Route for the Home/Welcome page
@app.route('/')
def index():
    return render_template('index.html')

# Route for the About page
@app.route('/about')
def about():
    return render_template('about.html')

# Route for the Analytics page
@app.route('/analytics')
def analytics():
    return render_template('analytics.html')

# Route for the Prediction page
@app.route('/predict', methods=['GET', 'POST'])
def predict_datapoint():
    if request.method == 'GET':
        # Just show the empty form
        return render_template('predict.html')
    else:
        try:
            # 1. Capture coordinates generated by the frontend JS (Map clicks or Search)
            p_lat_str = request.form.get('pickup_latitude')
            p_lon_str = request.form.get('pickup_longitude')
            d_lat_str = request.form.get('dropoff_latitude')
            d_lon_str = request.form.get('dropoff_longitude')
            
            # Validation: Ensure the user actually selected locations before submitting
            if not p_lat_str or not d_lat_str:
                return render_template('predict.html', 
                                       error_message="Please select locations on the map before predicting.")

            p_lat, p_lon = float(p_lat_str), float(p_lon_str)
            d_lat, d_lon = float(d_lat_str), float(d_lon_str)

            # 2. Capture and format the Date and Time from the split HTML inputs
            pickup_date = request.form.get('pickup_date')
            pickup_time = request.form.get('pickup_time')
            
            # Combine them into the format expected by LightGBM (YYYY-MM-DD HH:MM:SS)
            formatted_datetime = f"{pickup_date} {pickup_time}:00"

            # 3. Initialize Data Bridge
            data = CustomData(
                vendor_id=int(request.form.get('vendor_id')),
                passenger_count=int(request.form.get('passenger_count')),
                pickup_latitude=p_lat,
                pickup_longitude=p_lon,
                dropoff_latitude=d_lat,
                dropoff_longitude=d_lon,
                store_and_fwd_flag=request.form.get('store_and_fwd_flag'),
                pickup_datetime=formatted_datetime
            )
            
            # 4. Generate prediction using the globally loaded pipeline
            pred_df = data.get_data_as_data_frame()
            prediction_output = predict_pipeline.predict(pred_df)
            
            # 5. Extract total seconds and format for the UI
            total_seconds = int(prediction_output[0])
            minutes = total_seconds // 60
            seconds = total_seconds % 60
            formatted_time = f"Approximately {minutes} Minutes {seconds} Seconds"
            
            # 6. Render the template with the exact variables the HTML Jinja expects
            return render_template('predict.html', 
                                   total_seconds=total_seconds,
                                   formatted_time=formatted_time)
                                   
        except Exception as e:
            # Basic error handling to keep the app from crashing
            return f"An error occurred in processing: {str(e)}"

if __name__ == "__main__":
    # Changed host to 0.0.0.0 so the container is accessible from the outside network
    app.run(host="0.0.0.0", port=5000, debug=True, use_reloader=False)