name: NYC Taxi MLOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.14
      uses: actions/setup-python@v4
      with:
        python-version: "3.14"

    # Step 3: Install dependencies, lint, and run unit tests
    - name: Install Dependencies & Test
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest
        # Catch syntax errors
        flake8 src app.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # Run unit tests to ensure the server boots correctly
        pytest test_app.py

    # Step 4: Securely connect to AWS using GitHub Secrets
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 5: Log in to the Elastic Container Registry (ECR)
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Step 6: Build the container and push it to the vault
    - name: Build, Tag, and Push Docker Image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: urbanflow-ai
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG